### ISSUE TITLE
undefined reference to `_ck_assert_failed'

### ISSUE THREAD

**Issue by rpathani** [libcheck/check#130]
I have used check framework  in my project. On Fedora and Ubuntu 16.06, RHEL 7.3 we are not getting this issue with check. But on CentOS  7 we are getting build error because of 
more undefined references to `_ck_assert_failed' follow
collect2: error: ld returned 1 exit status
make[2]: *** [hsa_agent] Error 1
make[1]: *** [CMakeFiles/hsa_agent.dir/all] Error 2
make: *** [all] Error 2

[taccuser@HY-IN-SC01-153 ld.so.conf.d]$ ldconfig -p | grep libcheck
        libcheck.so.0 (libc6,x86-64) => /lib64/libcheck.so.0
        libcheck.so (libc6,x86-64) => /lib64/libcheck.so

**Comment by brarcher** [comment]
I created a VM with CentOS 7 and reproduced this while attempting to compile Check's example, though in a convoluted way which may not be the issue you are hitting. It turns out that CentOS provides Check 0.9.9 from 2012 in is repository. In that release many of the assert function funneled to ```_ck_assert_msg()```. This was changed in 2013 to ```_ck_assert_failed()```. I was able to reproduce a similar build failure by trying to build a more recent version of Check, then trying to compile the test program to point to the older version of Check. I made a mistake and I ended up pointing to the old version of library but the new version of the header file. As a result, the compiler was looking for _ck_assert_failed, but it did not exist in 0.9.9. Note that with a clean install of CentOS there was no issue.

If this is not similar to what you encountered, can you provide more details?

**Comment by brarcher** [comment]
I've not heard anything back. If you are still having this issue and your steps are different from what I tried, please re-open.
