### ISSUE TITLE
Debian Apt not installing on Ubuntu 16.04 Server

### ISSUE THREAD

**Issue by rizasif** [libcheck/check#153]
I have Ubuntu Server 16.04 (Terminal Interface) on my machine. When I do ```sudo apt-get install check``` It successfully installs the packages. However, the cmake cannot find the required package while running _CMakeLists.txt_. Moreover when I execute ```ldconfig -p | grep check```, the result is the following screenshot:
![image](https://user-images.githubusercontent.com/8410351/35442814-625c50a8-02ca-11e8-9721-a6f722891df2.png)

In contrast, the same cmake project builds fine on my Ubuntu Desktop 14.04 and executing ```ldconfig -p | grep check``` gives the following:
![image](https://user-images.githubusercontent.com/8410351/35442892-a7ef4530-02ca-11e8-8060-7b22208ae8f0.png)

When I view the _/usr/lib/x86_64-linux-gnu/_ folder in my 16.04 machine then it doesn't contain any _libgstcheck_ files. My guess is that they are not being installed or the path is different.

My cmake file is provided below, that I execute on both systems:
```https://github.com/rizasif/libsignal-protocol-c/blob/master/tests/CMakeLists.txt```

Kindly if you can check the issue.

**Comment by brarcher** [comment]
Are you finding that on Ubuntu Server 16.04 the libcheck library is
installed to /usr/local/lib instead of /usr/lib? That is odd, I wonder why
the package creator decided to install the library there. pkg-config may
not be looking under /usr/local/lib, or more specifically is not looking
for config files under /usr/local/lib/pkgconfig. Try pointing the
PKG_CONFIG_PATH environment variable to /usr/local/lib and see if your
build can find libcheck.

On Ubuntu 14.04 desktop are you seeing that libcheck is installing as lib
*gst*check? I think that might be GstCheck
<https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-libs/html/gstreamer-libs-GstCheck.html>
instead. Is Check installed on your Ubuntu 14.04 desktop machine?

**Comment by rizasif** [comment]
I don't understand either, after installing, auto removeing and restarting the machine couple of times did the work. I guess it was a problem with the virtual machine.
