### ISSUE TITLE
Testing a library, is it possible?

### ISSUE THREAD

**Issue by mcondarelli** [libcheck/check#169]
Hi,
I have to test a library, this means I need to set-up a series of use-cases using the lib.

Problem is I would like to insert some assertions *in* the library code, in order to verify some internal working not normally visible from outside.
Observing from "outside the lib API" could be insufficient.
I *can* compile the lib with special code enabled, but I'm unsure if this is supported and how.

Any pointer would be welcome.

**Comment by brarcher** [comment]
Testing a library is certainly possible. If you want to have asserts in the library that are not enabled in production code, the [man page for assert()](http://man7.org/linux/man-pages/man3/assert.3.html) says that:
```
If the macro NDEBUG is defined at the moment <assert.h> was last
included, the macro assert() generates no code, and hence does
nothing at all.  It is not recommended to define NDEBUG if using
assert() to detect error conditions since the software may behave
non-deterministically.
...
assert() is implemented as a macro; if the expression tested has
side-effects, program behavior will be different depending on whether
NDEBUG is defined.  This may create Heisenbugs which go away when
debugging is turned on.
```
That is, if you do not want asserts enabled in production code you could compile it with -DNDEBUG and add asserts as you see fit. You will need to be careful to not put business logic into the asserts, such as:
```
int fd;
assert( (fd = open(filename, "r")) != 0);
```
as the assert() will do nothing with NDEBUG defined, in which case this example would never open the file in production. Instead, asserts would need to only check conditions, such as:
```
int fd = open(filename, "r");
assert(fd != 0);
```

If you want to conditionally enable or disable asserts, assuming you were using autotools [and if not, do something similar in your build system] you could define a flag such as ```--enable-asserts```. By default asserts would be disabled. You would run the unit tests both with and without the flag; with to check the asserts do not fail, and without just in case an assert has business logic and a test fails anyway.

Hope it is helpful.

**Comment by mcondarelli** [comment]
Thanks @brarcher,
I seem to have not been clear enough.

What I really meant is:

Can I "just" `#include <check.h>` into my lib sources, intersperse liberally with `ck_assert_xxx()` calls and expect test programs (in another source file) to pick up and report errors?

TiA!

**Comment by brarcher** [comment]
Oh, I misunderstood. I see what you are trying to do.

I do not think that linking libcheck into the library is the best approach. The assertions in Check assume it is run within a unit test, and their behavior outside of a unit test is not defined. The library is targeted for unit test programs, which are stand-alone applications that exercise a library or code under test.

You could combine libcheck and assert() to get closer to the test coverage you are trying for. To do this, create a unit testing program that defines tests to be run that use the library. The library can be built to enable assert(). You would be creating checks both in the unit test (using Check's ck_ macros) and checks in the library (using assert()). If either of these hit a failure during a unit test the test would fail and be reported. This assumes that the tests are running with fork mode enabled (which is the default on Linux/Unix/MacOS). 

If your library is on Windows (where fork() is not supported), the asserts will instead kill your unit test program. That is OK, as long as you are using a logging type that reports when the tests are all complete, such as TAP. Otherwise, you could stop running tests and not know that all the tests did not finish.

Does this get you closer to what you are trying to achieve?

**Comment by brarcher** [comment]
If there is anything else I can provide guidance, let me know. In the meantime, I'll close this issue.
