### ISSUE TITLE
cmake support in Linux 

### ISSUE THREAD

**Issue by aristanemi** [libcheck/check#173]
Documentation says that currently official support using cmake build system is given for windows machines. 
Is this still valid ?

Actually i used cmake in Ubuntu machine and build is through. So far i havn't experienced any problems.

**Comment by brarcher** [comment]
CMake should work on Linux. There are automated tests run for CMake on Linux to prevent breakage. However, there are options and checks in the autotools build which are not ported to the CMake build. These enable or disable various features. Because of this the autotools build is considered official, and if the CMake build happens to work that is OK but it is not officially supported. If one day the features in the autotools are fully ported to the CMake build I'll probably drop autotools support and only provide CMake.
