### ISSUE TITLE
Cannot make the example

### ISSUE THREAD

**Issue by greenlaw110** [libcheck/check#48]
Error message:

```
Scanning dependencies of target money
[ 33%] Building C object src/CMakeFiles/money.dir/money.c.o
Linking C static library libmoney.a
[ 33%] Built target money
Scanning dependencies of target main
[ 66%] Building C object src/CMakeFiles/main.dir/main.c.o
Linking C executable main
[ 66%] Built target main
Scanning dependencies of target check_money
[100%] Building C object tests/CMakeFiles/check_money.dir/check_money.c.o
Linking C executable check_money
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcheck_pic.a(check_pack.o): undefined reference to symbol '__pthread_unregister_cancel@@GLIBC_2.3.3'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tests/check_money] Error 1
make[1]: *** [tests/CMakeFiles/check_money.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by brarcher** [comment]
I wonder if this is the same issue which is documented in [this](https://sourceforge.net/p/check/mailman/message/32835594/) mailing list exchange. Assuming that this is the same issue you mentioned in https://github.com/libcheck/check/issues/49, the issue is likely a combination of two things:
- Ubuntu (the upstream package maintainer of Check, probably) is distributing Check 0.9.10 as a static library
- Check 0.9.10 does not support pkg-config, which provides all the necessary flags one would need to link against Check
- Because Check is distributed as a static library, linking against Check requires the same link arguments that Check itself needed when it was built. As Check 0.9.10 does not support pkg-config, the example does not know what flags to use, and fails

Although perhaps an unsatisfactory answer, it seems that Ubuntu should update its package of Check to a later version that supports pkg-config. This would resolve the issue.

In the meantime, you can attempt a few different things to avoid this.

1. Compile Check 0.10.0 from source, install it, and use it, or
2. Add the necessary flags to the example's Makefile generating script; if you want to use the configure script the following (mentioned in the email thread) should do the trick:
```
AC_SEARCH_LIBS([pthread_create], [pthread])
```
Not sure what would need to be added to the CMakeLists.txt file off-hand to achieve the same thing.

**Comment by ProfessorKaos64** [comment]
I get this same issue when trying to compile librepo. See the autolinked post above this.

**Comment by ProfessorKaos64** [comment]
Ok, compiling with shared libs worked for me.

**Comment by brarcher** [comment]
Is this issue now resolved?

**Comment by ProfessorKaos64** [comment]
For me, yes.

**Comment by Gavxn** [comment]
I know this issue is old if you're using Cmake like me, add `find_package(Threads REQUIRED)` and `target_link_libraries(my_app ${CHECK_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT})` and your program should compile.

Blame Google Search for this necro-post.

**Comment by oliversheridanmethven** [comment]
I am getting this exact issue and am unclear how to implemented the above solutions. 

1. @mdeguzis  - Compiling with shared libraries? Does this mean changing the `STATIC` word in the `CMakeLists.txt` file to `SHARED`. I have tried this with no success.  
2. @brarcher  - I have downloaded and installed check-0.12.0 and built from source using cmake (as per the instructions on https://github.com/libcheck/check) with no problems. I have not changed the configure file (as I've used CMake), and this issue should be resolved (cf. issue #91 linked above).

Still I am getting the exact same error message as in the original post.
