### ISSUE TITLE
Please create proper release tarballs

### ISSUE THREAD

**Issue by lundmar** [libcheck/check#51]
Moving to github is great :+1: but please don't let that stop you from creating proper release tarballs. Meaning tarballs which include a ready to use configure script and not those half baked auto generated tarballs that github produces. Please use that sweet 'make dist' and upload the tarball as part of the github release notes.

Thank you.

**Comment by brarcher** [comment]
I think that all the release since the move to GitHub (e.g. 0.10.0) also included a tarball generated using the dist make target. The 0.10.0 tarball can be found in the Release section:

![screen shot 2016-06-15 at 9 15 18 am](https://cloud.githubusercontent.com/assets/5264535/16081055/c00bdd1c-32d9-11e6-8395-402389421b29.png)

Did I miss a release at some point which did not have a tarball? I certainly plan on providing tarballs for releases. Or, is your comment really "please keep it up"? If so, will do!

**Comment by lundmar** [comment]
First, my apology - you have indeed release a proper tarball :+1: 
In my hurry I didn't read the release note but went straight to the listed files in the Downloads section of the release note - where releases are usually attached. Obviously I didn't notice the tarball link embedded in the release note.
Sorry, keep up the good work :smile:

**Comment by brarcher** [comment]
Hm, I see how the Downloads section at the bottom can be confusing. I'm not sure how to disable that, as it seems that GitHub is automatically adding it. If you happen to know a way, please let me know and I can look into it.

**Comment by lundmar** [comment]
Since it is not possible to remove the Downloads section I think your best option is to simply to use it and attach the release file there instead of the custom link. Also, you might want to consider making signed releases (as supported by github) and attach eg. a check-0.10.0.tar.gz.asc file so that users and package maintainers can verify origin.

**Comment by brarcher** [comment]
Your comment about supporting signed releases is a good idea. I've added https://github.com/libcheck/check/issues/52 to track it:
